name: Re-order resources

on:
  workflow_dispatch:

jobs:
  reorder:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    # checkout repos
    - uses: actions/checkout@v3
    - name: Checkout ckan-admin-scripts repo
      uses: actions/checkout@v3
      with:
        repository: metaodi/ckan-admin-scripts
        path: ckan-admin-scripts

   # Setup Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/automation-requirements.txt
        pip install -r ckan-admin-scripts/requirements.txt
        sudo apt-get install jq
    
    # run the scripts
    - name: Reorder the resources
      env:
        CKAN_API_KEY: ${{ secrets.ckan_api_key }}
        CKAN_BASE_URL: ${{ secrets.ckan_base_url }}
      run: |
        ckanapi action package_search q="tags:sachdaten" rows=500 -r $CKAN_BASE_URL | jq -r ".results|.[]|.name" > dataset_list.txt
        wc -l dataset_list.txt
        cat dataset_list.txt
        cat dataset_list.txt | python ckan-admin-scripts/order_resources.py
    
    - name: Notify telegram failure
      if: ${{ failure()  || cancelled() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ERROR_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          🔴 [Reorder Resources Job Failed](https://github.com/opendatazurich/opendatazurich.github.io/actions/runs/${{ github.run_id }}?check_suite_focus=true)
