name: Tagger for CKAN datasets

on:
  schedule:
    - cron:  '4/15 * * * *' # every 15min
  workflow_dispatch:

jobs:
  tagger:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production

    steps:
    # checkout repos
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install requirements
      run: uv pip install -r automation/automation-requirements.txt
      env:
        UV_SYSTEM_PYTHON: 1
    
    # run the scripts
    - name: Tag CKAN datasets
      env:
        CKAN_API_KEY: ${{ secrets.ckan_api_key }}
        CKAN_BASE_URL: ${{ secrets.ckan_base_url }}
      run: |
        python automation/tagger/tagger.py -c automation/tagger/config.yml
      
    - name: Notify telegram failure
      if: ${{ failure()  || cancelled() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ERROR_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          🔴 [CKAN tagger job Failed](https://github.com/opendatazurich/opendatazurich.github.io/actions/runs/${{ github.run_id }}?check_suite_focus=true)
