name: Update vbz_frequenzen_hardbruecke data

on:
  schedule:
    - cron:  '*/15 * * * *' # every 15min
  workflow_dispatch:

jobs:
  update_data_py:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/automation-requirements.txt
        
    - name: Prepare data
      env:
        VBZ_SSZ_USER_N: ${{ secrets.VBZ_SSZ_USER_N }}
        VBZ_SSZ_PASSWORD_N: ${{ secrets.VBZ_SSZ_PASSWORD_N }}
      run: automation/vbz_frequenzen_hardbruecke/update_data.sh

    - name: Upload file to CKAN
      env:
        CKAN_BASE_URL: ${{ secrets.CKAN_BASE_URL }}
        CKAN_API_KEY: ${{ secrets.CKAN_API_KEY }}
        SSL_VERIFY: ${{ secrets.SSL_VERIFY }}
      run: |
        year=$(date +'%Y')
        python automation/upload_resource_to_ckan_with_patch.py -f automation/vbz_frequenzen_hardbruecke/frequenzen_hardbruecke_${year}.csv -d vbz_frequenzen_hardbruecke
        python automation/upload_resource_to_ckan_with_patch.py -f automation/vbz_frequenzen_hardbruecke/frequenzen_hardbruecke_${year}.parquet -d vbz_frequenzen_hardbruecke

    - name: Update CKAN metadata
      env:
        CKAN_BASE_URL: ${{ secrets.CKAN_BASE_URL }}
        CKAN_API_KEY: ${{ secrets.CKAN_API_KEY }}
        SSL_VERIFY: ${{ secrets.SSL_VERIFY }}
      run: |
        python automation/xls_to_meta_xml.py -f automation/vbz_frequenzen_hardbruecke/Frequenzen_Hardbruecke_Meta.xlsx --outfile automation/vbz_frequenzen_hardbruecke/meta.xml
        python automation/update_metadata.py -d vbz_frequenzen_hardbruecke -f automation/vbz_frequenzen_hardbruecke/meta.xml

    - name: Notify telegram failure
      if: ${{ failure()  || cancelled() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ERROR_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          🔴 [VBZ Frequenzen Job Failed](https://github.com/opendatazurich/opendatazurich.github.io/actions/runs/${{ github.run_id }}?check_suite_focus=true)
