name: Update Download Statistics

on:
  push:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch:
    inputs:
      USE_ROLLING_1_MONTH:
        description: "Use rolling 1-month file"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  update_data_py:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install requirements
      run: uv pip install -r automation/automation-requirements.txt
      env:
        UV_SYSTEM_PYTHON: 1
        
    - name: Update data
      env:
        CKAN_BASE_URL: ${{ secrets.CKAN_BASE_URL }}
        CKAN_API_KEY: ${{ secrets.CKAN_API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        USE_ROLLING_1_MONTH: ${{ github.event.inputs.USE_ROLLING_1_MONTH || 'false' }}
      run: |
        year=$(date +'%Y')
        python automation/download_statistics/download_statistics.py ${year}

    - name: Upload file to CKAN
      env:
        CKAN_BASE_URL: ${{ secrets.CKAN_BASE_URL }}
        CKAN_API_KEY: ${{ secrets.CKAN_API_KEY }}
        SSL_VERIFY: ${{ secrets.SSL_VERIFY }}
      run: |
        year=$(date -d "yesterday" +'%Y')
        python automation/upload_resource_to_ckan_with_patch.py -f ogd_katalog_downloads_${year}.csv -d prd_ssz_ogd_katalog_downloads
        python automation/upload_resource_to_ckan_with_patch.py -f ogd_katalog_downloads_${year}.parquet -d prd_ssz_ogd_katalog_downloads


    - name: Notify telegram failure
      if: ${{ failure()  || cancelled() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ERROR_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          🔴 [VBZ Frequenzen Job Failed](https://github.com/opendatazurich/opendatazurich.github.io/actions/runs/${{ github.run_id }}?check_suite_focus=true)
